FROM golang:1.25-alpine

WORKDIR /app

# Dependencies
RUN apk add --no-cache git bash

RUN go install github.com/air-verse/air@latest

# Packages
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air"]
